import type { FinanceSaleWithLines } from './types'

// Shown until a Supabase project is connected, so the app is never a blank
// screen. Mirrors the shape real rows will take once nextslot and shop
// admin syncing is switched on.
export const demoSales: FinanceSaleWithLines[] = [
  {
    id: 'demo-1',
    sale_date: '2026-08-24',
    customer_reference: 'Existing client, Claremont',
    source: 'nextslot_service',
    reconciliation_status: 'matched',
    payment_method: 'yoco_card',
    gross_amount_cents: 95000,
    yoco_payment_id: 'yoco_8841',
    booking_id: 'NS-2026-000311',
    shop_order_id: 'PB-2026-000184',
    notes: null,
    created_at: '2026-08-24T10:00:00Z',
    updated_at: '2026-08-24T10:00:00Z',
    finance_sale_lines: [
      {
        id: 'demo-1-a',
        sale_id: 'demo-1',
        line_type: 'service',
        description: 'Brazilian wax',
        quantity: 1,
        unit_price_cents: 70000,
        total_amount_cents: 70000,
        source_system: 'nextslot',
        source_record_id: 'NS-2026-000311',
        created_at: '2026-08-24T10:00:00Z',
      },
      {
        id: 'demo-1-b',
        sale_id: 'demo-1',
        line_type: 'call_out',
        description: 'Mobile call out',
        quantity: 1,
        unit_price_cents: 8000,
        total_amount_cents: 8000,
        source_system: 'nextslot',
        source_record_id: 'NS-2026-000311',
        created_at: '2026-08-24T10:00:00Z',
      },
      {
        id: 'demo-1-c',
        sale_id: 'demo-1',
        line_type: 'product',
        description: 'Post wax moisturiser',
        quantity: 1,
        unit_price_cents: 17000,
        total_amount_cents: 17000,
        source_system: 'shop_admin',
        source_record_id: 'PB-2026-000184',
        created_at: '2026-08-24T10:00:00Z',
      },
    ],
  },
  {
    id: 'demo-2',
    sale_date: '2026-08-22',
    customer_reference: 'Walk in',
    source: 'manual_product_sale',
    reconciliation_status: 'awaiting_review',
    payment_method: 'cash',
    gross_amount_cents: 45000,
    yoco_payment_id: null,
    booking_id: null,
    shop_order_id: null,
    notes: 'Sold before shop admin channel tagging was live.',
    created_at: '2026-08-22T14:20:00Z',
    updated_at: '2026-08-22T14:20:00Z',
    finance_sale_lines: [
      {
        id: 'demo-2-a',
        sale_id: 'demo-2',
        line_type: 'product',
        description: 'Refine and Restore jar',
        quantity: 1,
        unit_price_cents: 45000,
        total_amount_cents: 45000,
        source_system: 'manual',
        source_record_id: null,
        created_at: '2026-08-22T14:20:00Z',
      },
    ],
  },
  {
    id: 'demo-3',
    sale_date: '2026-08-20',
    customer_reference: 'Returning client, Bellville',
    source: 'nextslot_service',
    reconciliation_status: 'matched',
    payment_method: 'yoco_card',
    gross_amount_cents: 62000,
    yoco_payment_id: 'yoco_8790',
    booking_id: 'NS-2026-000298',
    shop_order_id: null,
    notes: null,
    created_at: '2026-08-20T09:15:00Z',
    updated_at: '2026-08-20T09:15:00Z',
    finance_sale_lines: [
      {
        id: 'demo-3-a',
        sale_id: 'demo-3',
        line_type: 'service',
        description: 'Full body massage',
        quantity: 1,
        unit_price_cents: 62000,
        total_amount_cents: 62000,
        source_system: 'nextslot',
        source_record_id: 'NS-2026-000298',
        created_at: '2026-08-20T09:15:00Z',
      },
    ],
  },
]
